#!/usr/bin/env python3
"""Extract team logos from prebuilt/csres.bin into main/cs_logo_data.c.

The resource pack holds: 64B header + font bitmap + 105 x 48x48 RGB565 + 105 x 20x20 RGB565.
Only the logo blocks are consumed here; the font lives in main/cs_font_cn16.c.
"""
import os, struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACK = os.path.join(ROOT, "prebuilt", "csres.bin")
OUT = os.path.join(ROOT, "main", "cs_logo_data.c")


def main():
    raw = open(PACK, "rb").read()
    magic = raw[:4]
    if magic != b"CSR2":
        raise SystemExit("bad pack magic %r" % magic)
    _, total, _, _, _, _, o48, l48, o20, l20, cnt = struct.unpack("<10I", raw[4:44])
    if total != len(raw) or l48 != cnt * 48 * 48 * 2 or l20 != cnt * 20 * 20 * 2:
        raise SystemExit("pack layout mismatch")

    def words(buf):
        return [struct.unpack_from("<H", buf, i)[0] for i in range(0, len(buf), 2)]

    w48 = words(raw[o48:o48 + l48])
    w20 = words(raw[o20:o20 + l20])

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// AUTO-GENERATED by tools/gen_logo_data.py -- do not edit.\n")
        fh.write("// Layout: %d teams, 48x48 then 20x20, RGB565 (one uint16 per pixel).\n\n" % cnt)
        fh.write("#include <stdint.h>\n\n")
        for name, ws in (("cs_logo48", w48), ("cs_logo20", w20)):
            fh.write("const uint16_t %s[%d] = {\n" % (name, len(ws)))
            for i in range(0, len(ws), 12):
                fh.write("  " + "".join("0x%04X," % v for v in ws[i:i + 12]) + "\n")
            fh.write("};\n\n")
    print("wrote %s (%d teams)" % (OUT, cnt))


if __name__ == "__main__":
    main()
