#!/usr/bin/env python3
"""Extract team logos from prebuilt/csres.bin into main/cs_logo_data.c.

The resource pack holds: 64B header + font bitmap + 105 x 48x48 RGB565 + 105 x 20x20 RGB565.
Only the logo blocks are consumed here; the font lives in main/cs_font_cn16.c.

Header(64B, little-endian uint32 from offset 4):
    magic "CSR2" | version | total | crc32(data[64:]) |
    font_off font_len | l48_off l48_len | l20_off l20_len | count | reserved
"""
import os
import struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACK = os.path.join(ROOT, "prebuilt", "csres.bin")
OUT = os.path.join(ROOT, "main", "cs_logo_data.c")


def main():
    raw = open(PACK, "rb").read()
    if raw[:4] != b"CSR2":
        raise SystemExit("bad pack magic %r" % raw[:4])

    (version, total, _crc, _font_off, _font_len,
     o48, l48, o20, l20, cnt) = struct.unpack_from("<10I", raw, 4)

    if version != 1:
        raise SystemExit("unsupported pack version %d" % version)
    if total != len(raw):
        raise SystemExit("pack size mismatch: %d vs %d" % (total, len(raw)))
    if l48 != cnt * 48 * 48 * 2 or l20 != cnt * 20 * 20 * 2:
        raise SystemExit("pack logo layout mismatch")
    if o48 + l48 > len(raw) or o20 + l20 > len(raw):
        raise SystemExit("pack logo offsets out of range")

    def words(buf):
        return [struct.unpack_from("<H", buf, i)[0] for i in range(0, len(buf), 2)]

    w48 = words(raw[o48:o48 + l48])
    w20 = words(raw[o20:o20 + l20])

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// AUTO-GENERATED by tools/gen_logo_data.py -- do not edit.\n")
        fh.write("// Real CS2 team logos, extracted from the verified resource pack.\n")
        fh.write("// Layout: %d teams, 48x48 then 20x20, RGB565 (one uint16 per pixel).\n\n" % cnt)
        fh.write("#include <stdint.h>\n\n")
        for name, ws in (("cs_logo48", w48), ("cs_logo20", w20)):
            fh.write("const uint16_t %s[%d] = {\n" % (name, len(ws)))
            for i in range(0, len(ws), 12):
                fh.write("  " + "".join("0x%04X," % v for v in ws[i:i + 12]) + "\n")
            fh.write("};\n\n")
    print("wrote %s (%d teams, %d + %d words)" % (OUT, cnt, len(w48), len(w20)))


if __name__ == "__main__":
    main()
